apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: chris-devops-example
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      targetPort: client
      port: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: chris-devops-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        version: v1
    spec:
      containers:
        - name: client
          image: dockerized-go-api_client:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /app
              name: hot-reload
          ports:
            - name: client
              containerPort: 4200
      volumes:
        - name: hot-reload
          hostPath:
            path: /Users/aklukas/projects/dockerized-go-api/client
